FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir jupyterlab plotly ipywidgets anywidget

COPY src/illustrator.ipynb src/illustrator.ipynb

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token="]
